---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
-- 탈퇴 회원 시퀀스 
DROP SEQUENCE SEQ_QUIT_MEMBER;
-- 팔로잉 시퀀스 
DROP SEQUENCE SEQ_FOLLOWING;
-- 게시판 시퀀스 
DROP SEQUENCE SEQ_BOARD;
-- 삭제 게시판 시퀀스 
DROP SEQUENCE SEQ_DEL_BOARD;
-- 댓글 시퀀스 
DROP SEQUENCE SEQ_COMMENT;
-- 삭제 댓글 시퀀스 
DROP SEQUENCE SEQ_DEL_COMMENT;
-- 카테고리 시퀀스
DROP SEQUENCE SEQ_CATEGORY;
-- 삭제 카테고리 시퀀스
DROP SEQUENCE SEQ_DEL_CATEGORY;
-- 경고 규정 시퀀스
DROP SEQUENCE SEQ_WARNING_LIST;
-- 누적 경고 횟수 시퀀스
DROP SEQUENCE SEQ_WARNING_NUM;
-- 취소된 누적 경고 횟수 시퀀스
DROP SEQUENCE SEQ_CANCLEED_WARNING_NUM;
-- 쪽지함 시퀀스
DROP SEQUENCE SEQ_TO_MESSAGE;
-- 삭제된 쪽지함 시퀀스
DROP SEQUENCE SEQ_DEL_TO_MESSAGE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

---------------------------------------------------
--------------------- 시퀀스 -----------------------
---------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT    NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY            NOCACHE NOCYCLE;

---------------------------------------------------
--------------------- 테이블 -----------------------
---------------------------------------------------
CREATE TABLE MEMBER(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , ENROLL_DATE TIMESTAMP     DEFAULT SYSDATE
    , MODIFY_DATE TIMESTAMP 
);

CREATE TABLE ADMIN(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , CATEGORY_NO   NUMBER          
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , REF_NO        NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(255)   
    , CHANGE_NAME   VARCHAR2(255)   NOT NULL UNIQUE
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N'
);

CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE CATEGORY(
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(30)    NOT NULL UNIQUE
);



---------------------------------------------------
--------------------- 외래키 -----------------------
---------------------------------------------------
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_BOARD FOREIGN KEY (WRITER_NO) REFERENCES ADMIN(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_ATTACHMENT_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'master' , '1234', '마스터');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin' , '1234', '운영자');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin01' , '1234', '운영자1');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin02' , '1234', '운영자2');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin031' , '1234', '운영자3');
COMMIT;

INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자유');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '운동');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '게임');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '개발');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자바');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '코딩');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '낚시');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '요리');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '댄스');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;