---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
-- 제제 이력 시퀀스 
DROP SEQUENCE SEQ_WARNING;
-- 경고 규정 시퀀스 
DROP SEQUENCE SEQ_WARNING_LIST;
-- 팔로우 시퀀스 
DROP SEQUENCE SEQ_FOLLOW;
-- 팔로잉 시퀀스 
DROP SEQUENCE SEQ_FOLLOWING;
-- 차단한 회원 시퀀스 
DROP SEQUENCE SEQ_BLOCK_MEMBER;
-- 댓글 시퀀스 
DROP SEQUENCE SEQ_COMMENTS;
-- 대댓글 시퀀스 
DROP SEQUENCE SEQ_RECOMMENT;
-- 주제 시퀀스 
DROP SEQUENCE SEQ_CATEGORY;
-- FAQ 시퀀스 
DROP SEQUENCE SEQ_FAQ;
-- 쪽지함 시퀀스 
DROP SEQUENCE SEQ_MESSAGE;
-- 게시판 시퀀스 
DROP SEQUENCE SEQ_BOARD;
-- 공지사항 시퀀스
DROP SEQUENCE SEQ_NOTICE;
-- QNA 시퀀스
DROP SEQUENCE SEQ_QNA;
-- 게시글 이미지 시퀀스
DROP SEQUENCE SEQ_BOARD_ATTACHMENT;

-- 회원 테이블
DROP TABLE MEMBER CASCADE CONSTRAINTS;
-- 제제 이력 테이블 
DROP TABLE WARNING CASCADE CONSTRAINTS;
-- 경고 규정 테이블 
DROP TABLE WARNING_LIST CASCADE CONSTRAINTS;
-- 팔로우 테이블 
DROP TABLE FOLLOW CASCADE CONSTRAINTS;
-- 팔로잉 테이블 
DROP TABLE FOLLOWING CASCADE CONSTRAINTS;
-- 차단한 회원 테이블 
DROP TABLE BLOCK_MEMBER CASCADE CONSTRAINTS;
-- 댓글 테이블 
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
-- 댓글 추천 테이블 
DROP TABLE COMMENTRECOMMEND CASCADE CONSTRAINTS;
-- 대댓글 테이블 
DROP TABLE RECOMMENT CASCADE CONSTRAINTS;
-- 주제 테이블 
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
-- FAQ 테이블 
DROP TABLE FAQ CASCADE CONSTRAINTS;
-- 쪽지함 테이블 
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
-- 게시판 테이블 
DROP TABLE BOARD CASCADE CONSTRAINTS;
-- 공지사항 테이블
DROP TABLE NOTICE CASCADE CONSTRAINTS;
-- QNA 테이블
DROP TABLE QNA CASCADE CONSTRAINTS;
-- 방문자 테이블
DROP TABLE VISITOR CASCADE CONSTRAINTS;
-- 추천인 테이블
DROP TABLE RECOMMEND CASCADE CONSTRAINTS;
-- 게시글 이미지 테이블
DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;


---------------------------------------------------
--------------------- 시퀀스 -----------------------
---------------------------------------------------

-- 제제 이력 시퀀스 
CREATE SEQUENCE SEQ_WARNING;
-- 경고 규정 시퀀스 
CREATE SEQUENCE SEQ_WARNING_LIST;
-- 팔로우 시퀀스 
CREATE SEQUENCE SEQ_FOLLOW;
-- 팔로잉 시퀀스 
CREATE SEQUENCE SEQ_FOLLOWING;
-- 차단한 회원 시퀀스 
CREATE SEQUENCE SEQ_BLOCK_MEMBER;
-- 댓글 시퀀스 
CREATE SEQUENCE SEQ_COMMENTS;
-- 대댓글 시퀀스 
CREATE SEQUENCE SEQ_RECOMMENT;
-- 주제 시퀀스 
CREATE SEQUENCE SEQ_CATEGORY;
-- FAQ 시퀀스 
CREATE SEQUENCE SEQ_FAQ;
-- 쪽지함 시퀀스 
CREATE SEQUENCE SEQ_MESSAGE;
-- 게시판 시퀀스 
CREATE SEQUENCE SEQ_BOARD;
-- 공지사항 시퀀스
CREATE SEQUENCE SEQ_NOTICE;
-- QNA 시퀀스
CREATE SEQUENCE SEQ_QNA;
-- 게시글 이미지 시퀀스
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT;

CREATE TABLE MEMBER (
	NO	                NUMBER		        
	, EMAIL	            VARCHAR2(30)	                       NOT NULL
	, PASSWORD	        VARCHAR2(20)		                   NOT NULL
	, NICK        	    VARCHAR2(20)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE    NOT NULL
	, INTRODUCTION	    VARCHAR2(50)		 
	, DEL_DATE    	    TIMESTAMP		                       
	, ADMIN_YN    	    CHAR(1)		        DEFAULT 'N'        NOT NULL
);

CREATE TABLE BOARD (
	NO	                NUMBER		
	, CATEGORY_NO	    NUMBER		                           NOT NULL
	, WRITER_NO	        NUMBER		                           NOT NULL
	, TITLE	            VARCHAR2(100)		                   NOT NULL
	, CONTENT	        VARCHAR2(2000)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, SECRET_YN	        CHAR(1)		        DEFAULT 'N'        NOT NULL
	, MODIFY_DATE	    TIMESTAMP		    
	, DEL_DATE	        TIMESTAMP		    
);

CREATE TABLE MESSAGE (
	NO	                NUMBER		
	, RECEIVER_NO	    NUMBER		                           NOT NULL
	, SENDER_NO	        NUMBER		                           NOT NULL
	, SEND_TIME	        TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, READ_TIME	        TIMESTAMP		    
	, TITLE	            VARCHAR2(50)		                   NOT NULL
	, CONTENT	        VARCHAR2(2000)	                       NOT NULL
);

CREATE TABLE WARNING_LIST (
	NO	                NUMBER		
	, TITLE	            VARCHAR2(50)		                   NOT NULL
	, POINT	            NUMBER		                           NOT NULL
);

CREATE TABLE WARNING (
	NO	                NUMBER		
	, WARNING_NO	    NUMBER		                           NOT NULL
	, MEMBER_NO	        NUMBER		                           NOT NULL
	, ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
);

CREATE TABLE CATEGORY (
	NO	                NUMBER		
	, TITLE	            VARCHAR2(20)		                   NOT NULL
);

CREATE TABLE COMMENTS (
	NO	                NUMBER		
	, BOARD_NO	        NUMBER		                           NOT NULL
	, WRITER_NO	        NUMBER		                           NOT NULL
	, CONTENT	        VARCHAR2(100)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, MODIFY_DATE	    TIMESTAMP		
	, DEL_DATE	        TIMESTAMP		
);

CREATE TABLE FOLLOW (
	NO	                NUMBER		
	, FOLLOWER_NO	    NUMBER		                           NOT NULL
	, MEMBER_NO	        NUMBER		                           NOT NULL
);

CREATE TABLE NOTICE (
	NO	                NUMBER		
	, CATEGORY_NO	    NUMBER		                           NOT NULL
	, WRITER_NO	        NUMBER		                           NOT NULL
	, TITLE	            VARCHAR2(100)		                   NOT NULL
    , CONTENT	        VARCHAR2(2000)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, HITS	            NUMBER		        DEFAULT 0          NOT NULL
);

CREATE TABLE RECOMMEND (
	BOARD_NO	        NUMBER		                           NOT NULL
	, REFERENCE_NO	    NUMBER		                           NOT NULL
);

CREATE TABLE VISITOR (
	BOARD_NO	        NUMBER		                           NOT NULL
	, VISITOR_NUM	    NUMBER		                           NOT NULL
);

CREATE TABLE QnA (
	NO	                NUMBER		
    , WRITER_NO	        NUMBER		                           NOT NULL
	, TITLE	            VARCHAR2(100)		                   NOT NULL
	, CONTENT	        VARCHAR2(1000)		                   NOT NULL
	, CREATED_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, ADMIN_NO	        NUMBER                                 
	, ANSWER_TITLE	    VARCHAR2(100)		                   
	, ANSWER_CONTENT	VARCHAR2(1000)		
	, ANSWER_DATE	    TIMESTAMP		
	, DEL_DATE	        TIMESTAMP		
);

CREATE TABLE FOLLOWING (
	NO	                NUMBER		
	, MEMBER_NO	        NUMBER		                           NOT NULL		
	, FOLLOWING_NO	    NUMBER		                           NOT NULL
);

CREATE TABLE COMMENTRECOMMEND (
	REFERENCE_NO	    NUMBER		                           NOT NULL
	, COMMENT_NO	    NUMBER		                           NOT NULL
);

CREATE TABLE BLOCK_MEMBER (
	NO	                NUMBER		
	, BLOCKER_NO	    NUMBER		                           NOT NULL
	, BLOCKED_NO	    NUMBER		                           NOT NULL
);

CREATE TABLE FAQ (
	NO	                NUMBER		
	, TITLE	            VARCHAR2(100)		                   NOT NULL
	, CONTENTS	        VARCHAR2(4000)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
    , MODIFY_DATE	    TIMESTAMP		    
	, DEL_DATE	        TIMESTAMP		                        
);

CREATE TABLE RECOMMENT (
	NO	                NUMBER		
	, COMMENT_NO	    NUMBER		                           NOT NULL
	, WRITER_NO	        NUMBER		                           NOT NULL
	, CONTENT	        VARCHAR2(100)		                   NOT NULL
	, ENROLL_DATE	    TIMESTAMP	      	DEFAULT SYSDATE    NOT NULL
	, MODIFY_DATE	    TIMESTAMP		
	, DEL_DATE	        TIMESTAMP		
);

CREATE TABLE BOARD_ATTACHMENT (
	NO	                NUMBER		
	, BOARD_NO	        NUMBER		                           NOT NULL
	, ORIGIN_NAME	    VARCHAR2(255)		                   NOT NULL
	, CHANGE_NAME	    VARCHAR2(255)		                   NOT NULL
	, UPLOAD_DATE	    TIMESTAMP		    DEFAULT SYSDATE    NOT NULL
	, DEL_YN	        CHAR(1)		        DEFAULT 'N'        NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	NO
);

ALTER TABLE MESSAGE ADD CONSTRAINT PK_MESSAGE PRIMARY KEY (
	NO
);

ALTER TABLE WARNING_LIST ADD CONSTRAINT PK_WARNING_LIST PRIMARY KEY (
	NO
);

ALTER TABLE WARNING ADD CONSTRAINT PK_WARNING PRIMARY KEY (
	NO
);

ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (
	NO
);

ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENTS PRIMARY KEY (
	NO
);

ALTER TABLE FOLLOW ADD CONSTRAINT PK_FOLLOW PRIMARY KEY (
	NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NO
);

ALTER TABLE QnA ADD CONSTRAINT PK_QNA PRIMARY KEY (
	NO
);

ALTER TABLE FOLLOWING ADD CONSTRAINT PK_FOLLOWING PRIMARY KEY (
	NO
);

ALTER TABLE BLOCK_MEMBER ADD CONSTRAINT PK_BLOCK_MEMBER PRIMARY KEY (
	NO
);

ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (
	NO
);

ALTER TABLE RECOMMENT ADD CONSTRAINT PK_RECOMMENT PRIMARY KEY (
	NO
);

ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT PK_BOARD_ATTACHMENT PRIMARY KEY (
	NO
);



---------------------------------------------------
--------------------- 외래키 -----------------------
---------------------------------------------------

-- 제제 이력 외래키
ALTER TABLE WARNING ADD CONSTRAINT FK_WARNING_WARNING_LIST FOREIGN KEY (WARNING_NO) REFERENCES WARNING_LIST(NO);
ALTER TABLE WARNING ADD CONSTRAINT FK_WARNING_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO);

-- 팔로우 외래키
ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOW_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO);
ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOW_MEMBER_FOLLOWER FOREIGN KEY (FOLLOWER_NO) REFERENCES MEMBER(NO);

-- 팔로잉 외래키
ALTER TABLE FOLLOWING ADD CONSTRAINT FK_FOLLOWING_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO);
ALTER TABLE FOLLOWING ADD CONSTRAINT FK_FOLLOWING_MEMBER_FOLLOWING FOREIGN KEY (FOLLOWING_NO) REFERENCES MEMBER(NO);

-- 차단한 회원 외래키
ALTER TABLE BLOCK_MEMBER ADD CONSTRAINT FK_BLOCK_MEMBER_BLOCKER FOREIGN KEY (BLOCKER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BLOCK_MEMBER ADD CONSTRAINT FK_BLOCK_MEMBER_BLOCKED FOREIGN KEY (BLOCKED_NO) REFERENCES MEMBER(NO);

-- 댓글 외래키
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(NO);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

-- 대댓글 외래키
ALTER TABLE RECOMMENT ADD CONSTRAINT FK_RECOMMENT_COMMENT FOREIGN KEY (COMMENT_NO) REFERENCES COMMENTS(NO);
ALTER TABLE RECOMMENT ADD CONSTRAINT FK_RECOMMENT_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

-- 댓글 추천 외래키
ALTER TABLE COMMENTRECOMMEND ADD CONSTRAINT FK_COMMENTRECOMMEND_COMMENT FOREIGN KEY (COMMENT_NO) REFERENCES COMMENTS(NO);
ALTER TABLE COMMENTRECOMMEND ADD CONSTRAINT FK_COMMENTRECOMMEND_MEMBER FOREIGN KEY (REFERENCE_NO) REFERENCES MEMBER(NO);

-- 쪽지함 외래키
ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_MEMBER_RECEIVER FOREIGN KEY (RECEIVER_NO) REFERENCES MEMBER(NO);
ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_MEMBER_SENDER FOREIGN KEY (SENDER_NO) REFERENCES MEMBER(NO);

-- 게시판 외래키
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);

-- 공지사항 외래키
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

-- QNA 외래키
ALTER TABLE QNA ADD CONSTRAINT FK_QNA_MEMBER_WRITER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE QNA ADD CONSTRAINT FK_QNA_MEMBER_ADMIN FOREIGN KEY (ADMIN_NO) REFERENCES MEMBER(NO);

-- 추천자 외래키
ALTER TABLE RECOMMEND ADD CONSTRAINT FK_RECOMMEND_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(NO);
ALTER TABLE RECOMMEND ADD CONSTRAINT FK_RECOMMEND_MEMBER FOREIGN KEY (REFERENCE_NO) REFERENCES MEMBER(NO);

-- 방문자 외래키
ALTER TABLE VISITOR ADD CONSTRAINT FK_VISITOR_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(NO);
ALTER TABLE VISITOR ADD CONSTRAINT FK_VISITOR_MEMBER FOREIGN KEY (VISITOR_NUM) REFERENCES MEMBER(NO);

-- 게시글 이미지
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_ATTACHMENT_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(NO);



---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------

COMMIT;
